spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    username: root
    password: '0987'
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: wall,stat,slf4j
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: 小蟑
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.zhp.bootweb01.*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
#
#  jdbc:
#    template:
#      query-timeout: 3

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
  #  mvc:
  #    static-path-pattern: /static/**
  profiles:
    active: test



mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true


info:
  appName: "小蟑"
  mysqlVersion: @project.version@
